### ISSUE TITLE
What is a style guide?

### ISSUE THREAD

**Issue by Bennykillua** [Bennykillua/Getting-started-in-Technical-Writing#13]
Please provide a brief definition of a style guide in two lines.

[File](https://github.com/Bennykillua/Getting-started-in-Technical-Writing/blob/main/Technical%20Writing%20Resources.md)

**Comment by slim-codes** [comment]
I'd like to work on this

**Comment by Bennykillua** [comment]
Thanks @slim-codes 


You can add the definition under the what is a style guide heading in this [file](https://github.com/Bennykillua/Getting-started-in-Technical-Writing/blob/main/Technical%20Writing%20Resources.md)

**Comment by slim-codes** [comment]
Alright! On it

**Comment by Bennykillua** [comment]
This has been closed by PR #25
