### ISSUE TITLE
Add a guide for Hacktoberfest

### ISSUE THREAD

**Issue by Bennykillua** [Bennykillua/Getting-started-in-Technical-Writing#22]
Add the article [here](https://github.com/Bennykillua/Getting-started-in-Technical-Writing/blob/main/Contributing%20as%20a%20technical%20writer.md)

**Comment by kvngkute** [comment]
@Bennykillua i will like to work on this

**Comment by Bennykillua** [comment]
Great!

**Comment by OdianoseEmmanuel** [comment]
I will like to work on this
