### ISSUE TITLE
Adding more examples of markdown syntax

### ISSUE THREAD

**Issue by Bennykillua** [Bennykillua/Getting-started-in-Technical-Writing#8]
The markdown file needs more syntax added to it. 

Here is a [link](https://github.com/Bennykillua/Getting-started-in-Technical-Writing/blob/main/Learning%20Markdown.md) to the file.

**Comment by lazyturd** [comment]
Hello, I would like to be assigned to this. Thank you

**Comment by Bennykillua** [comment]
Hi Ayomide, I have assigned this issues to you.
